apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: demo-go-0609 
  janus-idp.io/tekton: demo-go-0609
  backstage.io/kubernetes-id: demo-go-0609
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: demo-go-0609
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml